spring.application.name=UserNotes

spring.datasource.url=jdbc:mysql://localhost:3306/notesapp?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Dk9088946003@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
